apiVersion: v1
kind: Pod
metadata:
  name: mypod3
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: myfrontend
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: mypd
  restartPolicy: Always
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: myclaim101
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim101
  #annotations:
    #yummyNodeName: ubuntu-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-volume
